### ISSUE TITLE
sso.logoutRedirect needs documentation

### ISSUE THREAD

**Issue by willtran-** [spring-cloud/spring-cloud-security#65]
With that property set to false, it's up to you to add a LogoutHandler in your own OAuth2SsoConfigurerAdapter.configure(HttpSecurity), otherwise logout does nothing. With it set to true it will clear your access token from session, and sign you out of the authorization server (which I find quite useful).

**Comment by dsyer** [comment]
Signing out of the authorization server is highly variable. I think I hacked this together so it worked on Cloud Foundry for a demo, but I'm hesitant to call out this feature directly until we have time to discuss it a bit. Local logout (i.e. from the SSO client app) is a useful thing to be able to do via configuration, since it is boiler plate. But I'm not sure there is really a good generic single-logout scheme we can implement.

**Comment by willtran-** [comment]
If we can qualify that you're running in Cloud Foundry and you're using the UAA as the authorization server, then maybe this feature can be formalized. Should a CF-only feature be a feature in this project?

**Comment by dsyer** [comment]
We don't support logout declaratively any more and those features all moved to Spring Boot in 1.3 anyway. If we need to we can open a new issue over there.
