### ISSUE TITLE
Microservices Relay Credentials

### ISSUE THREAD

**Issue by jgasmi** [spring-cloud/spring-cloud-security#67]
I have 2 spring boot microservices (created with JHipster), and would like to relay my credentials from One microservice to another. I have seen a lot's of examples of how to use `OAuth2RestTemplate` with different `OAuth2ProtectedResourceDetails`, but with no success.

My use case is that I'm exposing some REST functions in Microservice A which have to consume another REST in microservice B and would like to use the same credentials and different clientId.

Any help please ?

**Comment by dsyer** [comment]
I'm not sure what you mean by "same credentials" and "different clientId" (since credentials are attached to a client generally), but I guess that "credentials" means the access token? If we ignore  the clientId, and you want to relay the incoming token you should make sure it has the correct audience (resource ids) and just pull it out of the `SecurityContext` and push it into the outgoing `OAuth2ClientContext`.
