### ISSUE TITLE
ResourceServerTokenServicesConfiguration does not create ResourceServerProperties

### ISSUE THREAD

**Issue by zhl-home1** [spring-cloud/spring-cloud-security#68]
I setup an oauth2 authserver and ui server. Both tested ok at first.
But 2 days before, after I download lastest build-snapshot or upgrade to gradle 2.4, I cant run my ui server.

I got this:

```
Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'org.springframework.security.config.annotation.web.configuration.WebSecurityConfiguration': Injection of autowired dependencies failed; nested exception is org.springframework.beans.factory.BeanCreationException: Could not autowire method: public void org.springframework.security.config.annotation.web.configuration.WebSecurityConfiguration.setFilterChainProxySecurityConfigurer(org.springframework.security.config.annotation.ObjectPostProcessor,java.util.List) throws java.lang.Exception; nested exception is org.springframework.beans.factory.BeanExpressionException: Expression parsing failed; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'org.springframework.cloud.security.oauth2.sso.OAuth2SsoConfiguration': Injection of autowired dependencies failed; nested exception is org.springframework.beans.factory.BeanCreationException: 
Could not autowire field: private org.springframework.security.oauth2.provider.token.ResourceServerTokenServices org.springframework.cloud.security.oauth2.sso.OAuth2SsoConfiguration.tokenServices; nested exception is org.springframework.beans.factory.BeanCreationException: 
Error creating bean with name 'org.springframework.cloud.security.oauth2.resource.ResourceServerTokenServicesConfiguration$RemoteTokenServicesConfiguration$UserInfoTokenServicesConfiguration': Injection of autowired dependencies failed; nested exception is org.springframework.beans.factory.BeanCreationException: 
Could not autowire field: private org.springframework.cloud.security.oauth2.resource.ResourceServerProperties org.springframework.cloud.security.oauth2.resource.ResourceServerTokenServicesConfiguration$RemoteTokenServicesConfiguration$UserInfoTokenServicesConfiguration.sso; nested exception is org.springframework.beans.factory.NoSuchBeanDefinitionException: 
No qualifying bean of type [org.springframework.cloud.security.oauth2.resource.ResourceServerProperties] found for dependency: expected at least 1 bean which qualifies as autowire candidate for this dependency. Dependency annotations: {@org.springframework.beans.factory.annotation.Autowired(required=true)}
```

I can see `ResourceServerPropertiesConfiguration` IN `ResourceServerTokenServicesConfigurations`, but `UserInfoTokenServicesConfiguration` cant get a instance.
This is strange to me...

**Comment by zhl-home1** [comment]
my spring io platform version 2.0.0.BUILD-SNAPSHOT
springCloudVersion = '1.0.2.BUILD-SNAPSHOT'
compile 'org.springframework.cloud:spring-cloud-starter-security'
runtime "org.springframework.boot:spring-boot-starter-security:${springBootVersion}"
runtime 'org.springframework.security.oauth:spring-security-oauth2'

**Comment by dsyer** [comment]
Are you getting snapshots of Spring Boot from the io platform?

**Comment by zhl-home1** [comment]
Yes, I am using io platform and spring-boot-gradle-plugin.
I found spring-boot-gradle-plugin override some dependencies.

**Comment by dsyer** [comment]
You are mixing Spring Boot 1.3 and Spring Cloud Security 1.0 (it doesn't work and it's not expected to work). Please change to a supported combination (1.3/1.1 or 1.2/1.0 respectively).

**Comment by zhl-home1** [comment]
I'm using  boot 1.2.4.RELEASE/ cloud Angel.SR3 and it works fine. Thank you!

**Comment by miguelfgar** [comment]
Hi @dsyer, guys,

I'm facing this same issue... I'm using Spring Boot 1.3.0-RELEASE and Spring Cloud Angel.SR4.
Is this combination supported? How can I check which combinations are valid?

Thank you

**Comment by dsyer** [comment]
No, that combination doesn't work. It's simple (and already documented in this issue or in the blog: https://spring.io/blog/2015/11/25/migrating-spring-cloud-apps-from-spring-boot-1-2-to-1-3).

**Comment by miguelfgar** [comment]
Thanks @dsyer,

I have aligned the versions properly (Spring boot 1.3.1-RELEASE, Brixton-M5) and made the upgrade changes as you described here: https://gist.github.com/dsyer/5b01276e9071c13492f7
I have implemented SSO with OAuth2 configured in ZuulProxy and using Token Relay to access microservice A and microservice B. With the proper versions everything is working fine.

However, I want microservice A to access microservice B. I'm implementing this using Oauth2RestOperations (OAuth2RestTemplate) in microservice A. The problem is that when OAuth2RestTemplate tries to retrieve the OAuth2Token from the context, is null. It should not be null as microservice A should have already the token in the context (and besides I know it is not expired).
Should this work? Do you think is a good approach (using OAuth2RestTemplate taking benefeit that the OAuth2Context has already the token to propagate it instead of asking for a new token to the oauth2 server)? Another option would be implement it with FeignClient and interceptors...
I'm pretty sure technically should work (correct me if I'm wrong, please) but I can't see what is wrong.
Spring Boot and Cloud versions are correct now, I don't use Spring Cloud dependencies except in the Zuulproxy (as I want to implement token relay not just SSO), the spring.oauth2 properties renamed to security.oauth2, and so on.. Everything looks good and in fact everything is working except OAuthRestOperations to call from microservice A to B.  
Any clue?

Thanks again for your help

**Comment by xiaohulu** [comment]
@chshawkn-pub Do you resolve your problem?
